# Generated by Django 4.1.13 on 2024-07-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='type',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('simple_sans_risque', 'Simple sans risque'),
                    ('simple_avec_risque', 'Simple avec des risques'),
                    ('compliqué_sans_risque', 'Compliqué sans risque'),
                    ('compliqué_avec_risque', 'Compliqué avec le risque')
                ],
                default='simple_sans_risque'
            ),
        ),
    ]
