# Generated by Django 4.1.13 on 2024-07-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ligne'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='etat',
            field=models.CharField(choices=[('Operateurr', 'Operateur'), ('Candidat', 'Candidat'), ('En Formation', 'En Formation')], default='Candidat', max_length=100),
        ),
    ]
