# Generated by Django 5.0.3 on 2024-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsableecoleformation',
            name='school_name',
        ),
        migrations.AddField(
            model_name='agent',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
