# Generated by Django 4.1.13 on 2024-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_personnel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='Effectif',
            field=models.IntegerField(default=0),
        ),
    ]
