# Generated by Django 4.1.13 on 2024-07-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personnel_ligne_alter_personnel_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='etat',
            field=models.CharField(choices=[('Operateur', 'Operateur'), ('Candidat', 'Candidat'), ('En Formation', 'En Formation')], default='Candidat', max_length=100),
        ),
    ]
