# Generated by Django 4.1.13 on 2024-07-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_personnel_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superviseur',
            name='ligne',
        ),
        migrations.AddField(
            model_name='ligne',
            name='superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.superviseur'),
        ),
        migrations.AddField(
            model_name='superviseur',
            name='lignes',
            field=models.ManyToManyField(related_name='superviseurs', to='api.ligne'),
        ),
    ]
