# Generated by Django 4.1.13 on 2024-06-20 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_agent_options_alter_agent_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='etat',
            field=models.CharField(blank=True, default='Candidat', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_test', models.CharField(max_length=100)),
                ('date_test', models.DateField()),
                ('formateurs', models.ManyToManyField(related_name='tests', to='api.formateur')),
                ('responsables_ecole_formation', models.ManyToManyField(related_name='tests', to='api.responsableecoleformation')),
            ],
        ),
        migrations.CreateModel(
            name='NoteTestPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteTest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=100)),
                ('date_creation_contrat', models.DateField()),
                ('duree_contrat', models.IntegerField()),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='tests',
            field=models.ManyToManyField(through='api.NoteTestPersonnel', to='api.test'),
        ),
    ]
