# Generated by Django 4.1.13 on 2024-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_agent_options_alter_agent_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='lignes',
            field=models.ManyToManyField(related_name='formateurs', to='api.ligne'),
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lignes', models.ManyToManyField(related_name='postes', to='api.ligne')),
            ],
        ),
    ]
