# Generated by Django 4.1.13 on 2024-08-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_departements', to='api.ligne')),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.segment')),
            ],
        ),
    ]
