# Generated by Django 4.1.13 on 2024-07-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_superviseur_ligne_ligne_superviseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.poste'),
        ),
        migrations.CreateModel(
            name='Polyvalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poste')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.superviseur')),
            ],
        ),
    ]
