# Generated by Django 4.1.13 on 2024-06-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_module_remove_formateur_lignes_delete_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lignes', models.ManyToManyField(related_name='postes', to='api.ligne')),
            ],
        ),
    ]
