# Generated by Django 4.1.13 on 2024-06-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='lignes',
            field=models.ManyToManyField(related_name='formateurs', to='api.ligne'),
        ),
    ]
