# Generated by Django 4.1.13 on 2024-07-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_polyvalence_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='polyvalence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='polyvalence',
            name='ligne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ligne'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='polyvalence',
            unique_together={('personnel', 'poste', 'ligne')},
        ),
    ]
