# Generated by Django 4.1.13 on 2024-06-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_formateur_lignes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(upload_to='modules/'),
        ),
    ]
